### ISSUE TITLE
Ability to set preferred soulbind for each profile

### ISSUE THREAD

**Issue by nisoda** [peti446/SwitchSwitch#10]
**Is your feature request related to a problem? Please describe.**
Problem with the add-on is that it's too good. I forget to swap soulbinds at the same time as changing ss profiles since the add-on makes it so easy to do the talents/gear all at once.

**Describe the solution you'd like**
I'd like the ability to set a preferred soulbind (e.g. Dreamweaver, Korayn, Emeni, etc. depending on covenant) for my talent/gearset profiles. These currently only require a rested area to change (similar to talents), and some specs highly benefit from swapping soulbinds in different encounters.

_Possible stretch goal features on top of this would be to 1) be able to set different soulbind paths (also only requires rested area to change) and 2) be able to set different conduits (assuming this no longer requires Forge of Bonds in a future patch)._

**Comment by peti446** [comment]
The latest version 2.1.9 Will include these changes ^^ You can now set like with gear sets preferred soul binds, for the 1) is something that will be looked into for future version. I will Keep this open for the time being.
