### ISSUE TITLE
Same talents with different gear sets and soulbinds does not respect the correct name for the profile in talents overview

### ISSUE THREAD

**Issue by timoage** [peti446/SwitchSwitch#11]
If you create two profiles with the same talents selected but with a different gear set or different soulbinds the name of the profile shown in the talents overview will always show the alphanumerically named last talent profile matching the selected talents and therefore confuse the user, because the user thinks he selected the wrong profile.

Profile named 1:
![image](https://user-images.githubusercontent.com/20972694/141375697-efe87bcd-2fad-4dc2-899e-31914f4f1722.png)

Profile named 2 (note: different soulbind):
![image](https://user-images.githubusercontent.com/20972694/141375788-38c948c0-76ec-454c-9da0-58cf8f8aec8c.png)

Selecting profile 1:
![image](https://user-images.githubusercontent.com/20972694/141375838-c54ab41f-7e3b-4886-acb5-963228233f36.png)

Close and open talents again:
![image](https://user-images.githubusercontent.com/20972694/141375873-c8099fe8-27e8-4dbd-99fe-83a547c712b5.png)
Still shows profile is one in chat but in talents overview it switched to 2

**Comment by peti446** [comment]
Interesting, I think it is not checking for the soul bind to determine the talent set you are in, this will need to be added to solve this.

**Comment by timoage** [comment]
The same is happening when you pick same talents and same soulbind but different gear set in two profiles. So I guess the check needs to be done there, too? Greetings

**Comment by peti446** [comment]
The same issue and will be resolved together.
