### ISSUE TITLE
SwitchSwitch does not recognize Kyrian ability to switch talents without tome

### ISSUE THREAD

**Issue by Coggles** [peti446/SwitchSwitch#5]
In Shadowlands the Kyrian covenant has the ability to switch talents without a tome, granted every four hours by their stewart.  SwitchSwitch still attempts to use a tome even when this ability has been activated.  The code needs to check for the player buff "Time to Reflect" and allow the talents to be changed without requiring or using a tome.

**Comment by peti446** [comment]
Right! Thanks for reporting update incoming!
