### ISSUE TITLE
Addon errors and not working properly

### ISSUE THREAD

**Issue by MagokSama** [peti446/SwitchSwitch#6]
Hello, 
I'm getting an error when I mouse over the minimap icon:

> Message: Interface\AddOns\SwitchSwitch\MinimapIcon.lua:18: bad argument #3 to 'format' (string expected, got nil)
> Time: Sun Jan 31 11:17:32 2021
> Count: 1
> Stack: Interface\AddOns\SwitchSwitch\MinimapIcon.lua:18: bad argument #3 to 'format' (string expected, got nil)
> [string "=[C]"]: ?
> [string "=[C]"]: in function `format'
> [string "@Interface\AddOns\SwitchSwitch\MinimapIcon.lua"]:18: in function `OnTooltipShow'+

And the addon has no functionality whatsoever on talent screen to create/delete or show the profiles. 
Havent tested anything else since its missing the core funcitonality.

**Comment by peti446** [comment]
Thanks for the report! Will be fixing this in the next couple of hrs
