### ISSUE TITLE
[BUG] Not prompting to swap specs on entering M+

### ISSUE THREAD

**Issue by lostmimic** [peti446/SwitchSwitch#8]
**Describe the bug**
When entering an M+ dungeon in Season 2, it is not asking me to swap over to the spec configured for it

**To Reproduce**
1. Go to 'any M+ dungeon in a different spec than the one configured for the zone'
2. Do not get prompted to swap specs

**Addon version:**
- Version 2.1.1

**Lua eror (if any):**

**Comment by lostmimic** [comment]
I edited the InstancesData.lua to test adding SoD and magically this started working after reloading it in...

**Comment by peti446** [comment]
Yhea, sorry it took me a bit to get the data in but this has been solved as mentioned in (https://github.com/peti446/SwitchSwitch/issues/9), as we do not have access to all affixes for all 12 weeks, the first 3 weeks have been added and as they release each Tuesday it will be added until we know all 12.
