### ISSUE TITLE
[BUG] Sanctum of Domination not supported

### ISSUE THREAD

**Issue by lostmimic** [peti446/SwitchSwitch#9]
**Describe the bug**
The SoD info needs to get added to InstanceData.lua

**To Reproduce**
N/A

**Addon version:**
- Version 2.1.1

**Lua eror (if any):**

**Comment by peti446** [comment]
Thanks for the report, all data for SoD and the new dungeon have been added in v2.1.2 (https://github.com/peti446/SwitchSwitch/commit/f481d9f947b2b35d7756c549de83bc01e4050a04).  @lostmimic
